title = "关于"
base_url = "http://localhost"
description = "canxin 的博客"
author = "canxin"
default_language = "zh-Hans"

theme = "duckquill"

compile_sass = true
minify_html = true
generate_feeds = true
feed_filenames = ["rss.xml", "atom.xml"]
build_search_index = true

taxonomies = [{ name = "tags", feed = true }]

[languages.en]
title = "About"
description = "canxin's blog."
generate_feeds = true
feed_filenames = ["rss.xml", "atom.xml"]
build_search_index = true
taxonomies = [{ name = "tags", feed = true }]

[markdown]
render_emoji = true
definition_list = true
lazy_async_image = true
insert_anchor_links = "left"
external_links_external = true
external_links_target_blank = true
external_links_no_follow = true
external_links_no_referrer = true
external_links_class = "external"
smart_punctuation = true
bottom_footnotes = true
github_alerts = true

[markdown.highlighting]
error_on_missing_language = false
style = "inline"
theme = "solarized-dark"

[search]
index_format = "fuse_json"

[extra]
default_theme = "dark"
accent_color = "#ff7800"
accent_color_dark = "#ffa348"
show_copy_button = true
show_reading_time = true
show_share_button = true
show_backlinks = true
toc = true
blurnail = true
issues_url = "https://github.com/canxin121/duckquill-blog/issues"
source_url = "https://github.com/canxin121/duckquill-blog"
favicon = "icons/favicon.png"
apple_touch_icon = "icons/apple-touch-icon.png"
styles = ["css/about-profile.css"]
scripts = ["js/mermaid-init.js"]

[extra.nav]
show_feed = true
show_theme_switcher = true
show_repo = false
links = [
  { url = "@/blog/_index.md", name = "Blog" }
]

[extra.footer]
links = []
socials = []
show_copyright = true
copyright = "© canxin, 2026"
show_powered_by = true
show_source = true
